Fix airdropOil transaction
CodeChain-io/codechain-helicopter pull request #23
Opened 2019-02-18 07:46 UTC by HoOngEe

Previously, the helicopter was continuously creating airdropOil Transactions under the assumption that the transaction sent just before will be successfully completed. Therefore, any single failing transaction among transactions can cause all transactions following it to fail.
To fix this problem the functionality which recovers the last successful transaction output asset and resend based on it,  is implemented.

2019-02-18 13:32 UTC, sgkim126 requested changes

2019-02-18 13:32 UTC, sgkim126 commented on index.ts
> +    while (pendingOilInfos[0]) {
```ts
while (pendingOilInfos.length !== 0) {
```

2019-02-18 13:32 UTC, sgkim126 commented on index.ts
> +        if (invoice) {
```ts
if (!invoice) {
    if (ifExpirationLimitExceeded || ifFailsInTheMiddle) {
        return {
            resetAsset: true,
            lastSuccessfulAsset
        };
    }
    break;
}

lastSuccessfulAsset = info.oilAsset;
pendingOilInfos.shift();
```

2019-02-18 13:32 UTC, sgkim126 commented on index.ts
> +    let lastSuccessfulAsset: Asset | undefined;
```ts
let lastSuccessfulAsset?: Asset;
```

2019-02-18 13:32 UTC, sgkim126 commented on index.ts
> +                if (!lastSuccessfulAsset) {
```ts
if (lastSuccessfulAsset == undefined) {
```

2019-02-18 13:32 UTC, sgkim126 commented on index.ts
> +                const iftrasnactionCompleted = invoice === true;
```ts
const isTrasnactionCompleted = invoice === true;
const isTransactionNotCompleted = invoice === null;
```

2019-02-19 02:12 UTC, HoOngEe commented on index.ts
> +    while (pendingOilInfos[0]) {
Fixed

2019-02-19 02:16 UTC, HoOngEe commented on index.ts
> +        if (invoice) {
Fixed

2019-02-19 02:16 UTC, HoOngEe commented on index.ts
> +                if (!lastSuccessfulAsset) {
Fixed

2019-02-19 02:24 UTC, HoOngEe commented on index.ts
> +                const iftrasnactionCompleted = invoice === true;
Fixed

2019-02-19 05:07 UTC, sgkim126 approved these changes

2019-02-19 08:31 UTC, majecty approved these changes
LGTM

2019-02-19 08:32 UTC, merged